openapi: 3.0.3
info:
  title: CBOMkit-theia
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
paths:
  /api/v1/image:
    post:
      summary: Generate CBOM from a Container Image
      requestBody:
        required: true
        content:
          application/json:    
            schema:
              type: object
              properties:
                image:
                  description: Identifier for the Container Image
                  example: "nginx"
                  type: string
                plugins:
                  type: array
                  example: 
                    - "javasecurity"
                    - "secrets"
                    - "certificates"
                  description: Plugins to activate
                  items:
                    type: string
                    description: Name of a plugin
                bom:
                  description: CBOM to verify/expand
                  $ref: "https://raw.githubusercontent.com/CycloneDX/specification/master/schema/bom-1.6.schema.json"
              required: 
                - image
      responses:
        '200':
          description: OK
          content:
            application/vnd.cyclonedx+json; version=1.6:
              schema:
                $ref: "https://raw.githubusercontent.com/CycloneDX/specification/master/schema/bom-1.6.schema.json"
        default:
          description: Unexpected error
          content:
            application/json: 
              schema:
                type: object
                properties:
                  error:
                    type: string
components:
  schemas:
      BOM:
        $ref: "https://raw.githubusercontent.com/CycloneDX/specification/master/schema/bom-1.6.schema.json"